### ISSUE TITLE
Connections 7 errors

### ISSUE THREAD

**Issue by Praveenk89** [HCL-TECH-SOFTWARE/connections-automation#136]
Hello Team,

We installed Connections 7.0 using Ansible on RHEL 8, but when we tried to access the Connections URL, we received the error "Check that the Common EAR is installed and running correctly." We then checked the Connections applications, and some were not running. We tried to start them manually, but nothing worked. So we finally checked the connection logs and discovered the following error logs in SystemOut.log on the server.

Error:1
8/30/21 15:52:16:600 AST] 000000dd HighwayClient W com.ibm.connections.highway.client.impl.db.HighwayClientImpl getSettingFromHighwayService CLFRO1025E: Cannot access back end database data, required bean is not available

Error2:
[8/30/21 15:52:47:765 AST] 000000c2 SystemErr     R Caused by: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=oracle/jdbc/pool/OracleConnectionPoolDataSource, offset=6
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.lang.ClassLoader.defineClassImpl(Native Method)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.net.URLClassLoader.defineClass(URLClassLoader.java:730)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.net.URLClassLoader.access$400(URLClassLoader.java:96)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1187)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.security.AccessController.doPrivileged(AccessController.java:770)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.net.URLClassLoader.findClass(URLClassLoader.java:605)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at com.ibm.ws.bootstrap.ExtClassLoader.findClass(ExtClassLoader.java:244)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:944)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.lang.ClassLoader.loadClass(ClassLoader.java:889)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at com.ibm.ws.bootstrap.ExtClassLoader.loadClass(ExtClassLoader.java:135)
[8/30/21 15:52:47:766 AST] 000000c2 SystemErr     R     at java.lang.ClassLoader.loadClass(ClassLoader.java:872)
[8/30/21 15:52:47:767 AST] 000000c2 SystemErr     R     at com.ibm.ws.rsadapter.DSConfigHelper.loadClass(DSConfigHelper.java:1526)
[8/30/21 15:52:47:767 AST] 000000c2 SystemErr     R     at com.ibm.ws.rsadapter.DSConfigHelper.createDataSource(DSConfigHelper.java:745)
[8/30/21 15:52:47:767 AST] 000000c2 SystemErr     R     at com.ibm.ws.rsadapter.spi.WSRdbDataSource.createNewDataSource(WSRdbDataSource.java:3029)
[8/30/21 15:52:47:767 AST] 000000c2 SystemErr     R     at com.ibm.ws.rsadapter.spi.WSRdbDataSource.<init>(WSRdbDataSource.java:1358)
[8/30/21 15:52:47:767 AST] 000000c2 SystemErr     R     at com.ibm.ws.rsadapter.spi.WSManagedConnectionFactoryImpl.setDataSourceProperties(WSManagedConnectionFactoryImpl.java:2679)

Thanks
PK

**Comment by stoeps13** [comment]
It seems your databases are not working correctly. Have you checked if Websphere can access the databases? (Open ISC and check in Resources > Datasource > Test connection)

There seems to be a problem with the JDK the JVMCFRE003 is a problem that the oracle driver is built with a different java version.

Which Websphere Version and Fixpack do you use?

Last point: RHEL 8 is officially not supported.

**Comment by Praveenk89** [comment]
> It seems your databases are not working correctly. Have you checked if Websphere can access the databases? (Open ISC and check in Resources > Datasource > Test connection)
> 
> There seems to be a problem with the JDK the JVMCFRE003 is a problem that the oracle driver is built with a different java version.
> 
> Which Websphere Version and Fixpack do you use?
> 
> Last point: RHEL 8 is officially not supported.

**Comment by Praveenk89** [comment]
> It seems your databases are not working correctly. Have you checked if Websphere can access the databases? (Open ISC and check in Resources > Datasource > Test connection)
> 
> There seems to be a problem with the JDK the JVMCFRE003 is a problem that the oracle driver is built with a different java version.
> 
> Which Websphere Version and Fixpack do you use?
> 
> Last point: RHEL 8 is officially not supported.
------------------------------------------------------------
Hello Christoph,

Thank you for your assistance.
The WebSphere and Java details are listed below.
Name                  IBM WebSphere Application Server Network Deployment
Version               8.5.5.19
Build Level           cf192103.03
Name                  IBM WebSphere SDK Java Technology Edition (Optional)
Version               8.0.6.15
Build Level           cf182034.03

We have an Oracle 19c DB server with the JAR files listed below.
ojdbc8.jar
xdb.jar

Thanks
PK

**Comment by stoeps13** [comment]
Please check if Websphere ISC can access the database

**Comment by Praveenk89** [comment]
Hello Christoph,

Thank you for your assistance. I have checked the database connection test using WebSphere but got the following error.
The test connection operation failed for data source metrics on server dmgr at node devapps-dmgr with the following exception: java.sql.SQLException: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=oracle/jdbc/pool/OracleConnectionPoolDataSource, offset=6. View JVM logs for further details. 

The WebSphere and Java details are listed below.
Name IBM WebSphere Application Server Network Deployment
Version 8.5.5.19
Build Level cf192103.03
Name IBM WebSphere SDK Java Technology Edition (Optional)
Version 8.0.6.15
Build Level cf182034.03

We have an Oracle 19c DB server with the JAR files listed below.
ojdbc8.jar
xdb.jar

Thanks
PK

**Comment by Praveenk89** [comment]
> Please check if Websphere ISC can access the database

Hello Christoph,

Thank you for your assistance. I have checked the database connection test using WebSphere but got the following error.
The test connection operation failed for data source metrics on server dmgr at node devapps-dmgr with the following exception: java.sql.SQLException: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=oracle/jdbc/pool/OracleConnectionPoolDataSource, offset=6. View JVM logs for further details.

The WebSphere and Java details are listed below.
Name IBM WebSphere Application Server Network Deployment
Version 8.5.5.19
Build Level cf192103.03
Name IBM WebSphere SDK Java Technology Edition (Optional)
Version 8.0.6.15
Build Level cf182034.03

We have an Oracle 19c DB server with the JAR files listed below.
ojdbc8.jar
xdb.jar

What could be the problem?

Thanks
PK

**Comment by Praveenk89** [comment]
Hello Christoph,

Thank you for your assistance. I have checked the database connection test using WebSphere but got the following error.
The test connection operation failed for data source metrics on server dmgr at node devapps-dmgr with the following exception: java.sql.SQLException: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=oracle/jdbc/pool/OracleConnectionPoolDataSource, offset=6. View JVM logs for further details.

The WebSphere and Java details are listed below.
Name IBM WebSphere Application Server Network Deployment
Version 8.5.5.19
Build Level cf192103.03
Name IBM WebSphere SDK Java Technology Edition (Optional)
Version 8.0.6.15
Build Level cf182034.03

We have an Oracle 19c DB server with the JAR files listed below.
ojdbc8.jar
xdb.jar

What could be the problem?

Thanks
PK

**Comment by stoeps13** [comment]
https://bfy.tw/RYoy

You need some WebSphere knowledge to dig into this. This project will not work if you never had contact with WebSphere or Connections.

**Comment by bmustan** [comment]
When you configure metrics, you will be using elastic search (component pack) not the database. The use of DB to do metrics is no longer supported.
