### ISSUE TITLE
updateInstaller throws "Invalid version number: Version number may be negative or greater than 255"

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#191]
Hi
I installed with the main branch from last Friday and wanted to uninstall the CFix, but get following error:
```
[root@cnx7-rh8-was updateInstaller]# export WAS_HOME=/opt/IBM/WebSphere/AppServer/
[root@cnx7-rh8-was updateInstaller]# ./updateWizard.sh 
Start of [ ./updateWizard.sh ]
Build 20201123_1449

Attempting to locate setupCmdLine.sh

**** WAS_CELL = ConnectionsCell
**** USER_INSTALL_ROOT = /opt/IBM/WebSphere/AppServer/profiles/Dmgr01
variables.xml file [/opt/IBM/WebSphere/AppServer/profiles/Dmgr01/config/cells/ConnectionsCell/variables.xml] can be loaded.
NEWS_HOME: null
IBM Connections Home: /opt/HCL/Connections
Xlib:  extension "RANDR" missing on display "localhost:10.0".
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:147)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:136)
	at com.ibm.icu.impl.ICUResourceBundle.<clinit>(ICUResourceBundle.java:922)
	at com.ibm.icu.impl.ZoneMeta.getSystemTimeZone(ZoneMeta.java:512)
	at com.ibm.icu.util.TimeZone.getTimeZone(TimeZone.java:598)
	at com.ibm.icu.util.TimeZone.getDefault(TimeZone.java:703)
	at com.ibm.icu.util.Calendar.getInstance(Calendar.java:1579)
	at com.ibm.lconn.wizard.update.ui.wizardPage.FixInfoWizardPage.<init>(Unknown Source)
	at com.ibm.lconn.wizard.update.ui.wizardPage.Pages.createNewPage(Unknown Source)
	at com.ibm.lconn.wizard.update.ui.wizardPage.Pages.getPage(Unknown Source)
	at com.ibm.lconn.wizard.update.ui.UpdateWizard.addPages(Unknown Source)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:605)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1089)
	at org.eclipse.jface.window.Window.open(Window.java:790)
	at com.ibm.lconn.wizard.launcher.UpdateInstallerLauncher.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Invalid version number: Version number may be negative or greater than 255
	at com.ibm.icu.util.VersionInfo.getInstance(VersionInfo.java:194)
	at com.ibm.icu.impl.ICUDebug.getInstanceLenient(ICUDebug.java:65)
	at com.ibm.icu.impl.ICUDebug.<clinit>(ICUDebug.java:69)
	... 14 more
End of [ ./updateWizard.sh ]

[root@cnx7-rh8-was updateInstaller]# java
-bash: java: command not found
[root@cnx7-rh8-was updateInstaller]# /opt/IBM/WebSphere/AppServer/java/jre/bin/java -version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 8.0.6.20 - pxa6480sr6fp20ifix-20210112_01(SR6 FP20+IJ29969))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20210111_463465 (JIT enabled, AOT enabled)
OpenJ9   - bbe68d9
OMR      - 6ad3a34
IBM      - b7e48f4)
JCL - 20201119_01 based on Oracle jdk8u271-b09
```
So the version 1.8.0_271 is counted as > 255, I got an update from Support for updateInstaller some weeks ago. So I assume that updateInstaller needs a fix.

Regards
Christoph

**Comment by stoeps13** [comment]
Reason for the error, the updateInstaller wasn't updated with the playbook I used. (trial environment) Will check if the playbook contains the update roles
